catalog/admin.py, catalog/models.py, curation/Load_StudyName.py, curation/tools.py, pgs_web/settings.py
There were some changes to the underlying models (requires migrations), and settings - still missing methods to display the data (similar to Metrics).
=> Code adjustments to include Demographics of Samples

catalog/models.py, catalog/tables.py
- Implemented as Column_demographic class in tables.py
- To do: port this method to render in the API?
- Also added table descriptions to make the code a little more intuitive!
=> Display Demographics in Sample description tables (score development, PSS)

catalog/static/catalog/pgs.scss, catalog/templates/catalog/index.html, catalog/templates/catalog/pgs.html, catalog/views.py
Home page edits
PGS Page edits
To do: make PGS, Pub, Trait page titles more prominent (hard to see that the ID is the most important part)
=> Changes to the homepage text, and score page to make trait more prominent

catalog/models.py, catalog/templates/catalog/about.html, catalog/templates/catalog/index.html
@ens-lgil I marked where I think we should add a small button to link to the submission text
=> Changes from Mike's proofreading of the website

catalog/templates/catalog/about.html, catalog/templates/catalog/base.html, catalog/templates/catalog/download.html
@ens-lgil to add a FTP diagram
=> Update text+layout (Downloads page)

catalog/templates/catalog/about.html, catalog/templates/catalog/index.html
"multiplied their" -> "multiplied by their"
=> Fix small typos

catalog/models.py
Field name wasn't clear before, it's not a "PGS Model"
=> Update covariates field

catalog/tables.py
This will allow for either PMIDs or dois to be searched and returned. This allow allows  preprints to be returned (which are not indexed on PubMed)
=> Edit sample tables to forward to EuropePMC

catalog/models.py, curation/Load_StudyName.py, curation/tools.py
- Adds this information to the scoring file header creator
- Also adjusts curation template ingestion script to handle curation notes (v6 of the template)
=> Add license field to Score object.

curation/Load_StudyName.py, curation/tools.py
Checks whether cohorts exist/have descriptive names; duplicates short name as full name instead of using 'UNKNOWN'.
ToDo: improve cohort handling, warn about duplicates
=> Updates to template loading script

curation/imports/curation.py, curation/imports/study.py, curation/parsers/cohort.py, curation/parsers/demographic.py, curation/parsers/generic.py, curation/parsers/metric.py, curation/parsers/performance.py, curation/parsers/publication.py, curation/parsers/sample.py, curation/parsers/score.py, curation/parsers/trait.py, curation/template_parser.py, release/scripts/PGSFTPChecks.py
And replace some non-ascii characters
=> Improve Study import and its error reporting

catalog/tables.py, curation/parsers/generic.py, curation/parsers/metric.py, curation/parsers/performance.py, curation/template_parser.py, requirements_local.txt
Except the update of requirements_local.txt
=> Updates concerning the import data parsing

catalog/templates/catalog/docs/stats.html, catalog/views.py
And add the stats for the Reported Trait distribution
=> Add number of entries in header of the 'distribution' tables

curation_tracker/admin.py
Some import pages could be accessed without login
=> Hotfix: Added explicit login requirement for import pages

curation/imports/curation.py
The import step counter was not reset for each study.
=> Fix: Reinitialising step count for each study import

curation_tracker/admin.py, curation_tracker/templates/curation_tracker/release_ready.html
=> Curation tracker/1.2

pgs_web/constants.py
Link to curation guidelines v4
=> Link to curation guidelines v4

catalog/static/catalog/pgs.scss
Change MAE from light blue to pink, matches preprint data.
=> Update MAE in pgs.scss

catalog/context_processors.py, catalog/templates/catalog/docs/about.html, catalog/templates/catalog/docs/faq.html, catalog/templates/catalog/includes/citation.html, catalog/tests/test_models.py, pgs_web/constants.py, release/scripts/EuropePMCLinkage.py, rest_api/static/rest_api/openapi/openapi-schema.yml, rest_api/views.py
( + update of rest/info examples)
=> Added previous publication for PGS-Catalog citation and updated acknowledgements

catalog/static/catalog/pgs.scss, catalog/templates/catalog/pgs_catalog_django_tables2_browse.html
=> Prevent click on "..." in pagination buttons

catalog/static/catalog/pgs.scss, catalog/templates/catalog/docs/about.html, catalog/templates/catalog/docs/ancestry.html, catalog/templates/catalog/index.html, catalog/views.py, pgs_web/constants.py
=> Add banner (NIH)

curation/imports/scoring_file.py
Last import with big files (37M rows) caused OOM errors. The import is now done in smaller chunks.
=> Big files import memory optimisation

catalog/context_processors.py, catalog/templates/catalog/docs/about.html, catalog/templates/catalog/docs/faq.html, catalog/templates/catalog/index.html, pgs_web/constants.py
Added links to PGS Catalog seminar and pgs_calc tutorial.
Added link to metadata validator in _Submit_ documentation.
=> Updated homepage text and pgs_calc doc
